### PR TITLE
Add yuescript support

### LINKED ISSUE #188: Add Yuescript support
https://yuescript.org/

### PR DESCRIPTION
**Pull request by Tarik02**
Closes #188

### CODE REVIEW

**Comment by hack3ric** [comment]
Sorry for keeping at it, but I would be rather disappointed if this gets merged.

mlua is supposed to be Lua bindings. Yuescript is a language that compiles to Lua, not Lua. It is _bloating_ the simplicity-power-balanced library.

We won't see V8 supporting TypeScript in our lifetime. (Except for JS's [type annotation proposal](https://github.com/tc39/proposal-type-annotations), which may eventually become JS itself)

**Comment by Tarik02** [comment]
> Sorry for keeping at it, but I would be rather disappointed if this gets merged.
> 
> mlua is supposed to be Lua bindings. Yuescript is a language that compiles to Lua, not Lua. It is _bloating_ this simplicity-power-balanced library.
> 
> We won't see V8 supporting TypeScript in our lifetime. (Except for JS's [type annotation proposal](https://github.com/tc39/proposal-type-annotations), which may eventually become JS itself)

I understand your point, but the problem it is impossible to implement this in application itself. mlua does not give access to lua_State instance which is required to use yuescript. However it’s possible to create lua_State other way and then create mlua::Lua from it.

Another problem is that Yuescript uses lua VM itself and requires Lua headers to be compiled. This problem can actually be solved by editing lua-src and other arc crates is order to give access to headers without building lua vm (who wants to build lua twice?).

As you said before, you suggest doing transpilation before running, but it is not always possible and convenient (ex. short scripts that you run once). And one of problems is that Yuescript transpilation result can (theoretically) be affected by environment it is running on (OS, interpreter version, etc).

Having this in mlua module (which is actually a little more than just binding for lua now) is not good solution and I would be happy to have better solution meeting all these requirements.

**Comment by hack3ric** [comment]
@Tarik02  It sounds like a good idea providing an unsafe method that exposes the inner `lua_State` and use it in Yuescript.

**Comment by Tarik02** [comment]
Solved with https://github.com/khvzak/mlua/issues/188#issuecomment-1192919765

**Pull request closed without merging**
