### PR TITLE
Implement `AsChunk` for references

### PR DESCRIPTION
**Pull request by hack3ric**

### CODE REVIEW

**Comment by khvzak** [comment]
Curious, do you have any specific reason for this?
`Lua::load()` takes &T where `T: AsChunk` so you should be able to pass your reference directly?

**Comment by hack3ric** [comment]
> Curious, do you have any specific reason for this? `Lua::load()` takes `&T` where `T: AsChunk` so you should be able to pass your reference directly?

`&'static str` won't work here:

```rs
fn load_lua_code_in_local_set(x: impl for<'lua> AsChunk<'lua> + 'static) {
  tokio::task::spawn_local(async move {
    let lua = Lua::new();
    lua.load(&x).exec_async().await
  });
}

fn do_something() {
  // the trait bound `for<'lua> &str: mlua::AsChunk<'lua>` is not satisfied
  // the following other types implement trait `mlua::AsChunk<'lua>`:
  //   std::string::String
  //   str
  load_lua_code_in_local_set("print 'Hello, world!'");
}
```

**Comment by khvzak** [comment]
I see, thanks!
Unfortunately this will not work for types generated by the `chunk!` macro as they are not `'static` 😞 

I'm happy to merge the PR, just want to make sure what kind of problem this would solve.
As you can always write a sort of:
```
    fn load_lua_code_in_local_set(x: &'static (impl for<'lua> AsChunk<'lua> + ?Sized)) {
        tokio::task::spawn_local(async move {
            let lua = Lua::new();
            lua.load(x).exec_async().await;
        });
    }
```

**Comment by hack3ric** [comment]
But this will also prevent it from passing owned `AsChunk` types such as `String`, `PathBuf` and (presumably in my project) `Uri`.

This is a quite niche PR indeed; maybe I'll just manually load code into buffer and use `impl AsRef<[u8]>`. If I need to use `chunk!`, I'd directly use `spawn_local` without a function wrapper.

Closing this PR since my problem is solved. Thanks!

**Pull request closed without merging**
