### PR TITLE
Add Lua::load_file function

### LINKED ISSUE #139: binds to luaL_loadfile
It would be very convenient to have bindings to the `luaL_loadfile` function from mlua in order to easily load lua files.

EDIT: I'd be happy to contribute :D

### PR DESCRIPTION
**Pull request by LordMZTE**
I had a go at implementing a `load_file` function that uses lua's native `luaL_loadfile` function. This makes it easier to load files.

Feedback would be greatly appreciated!

closes #139

### CODE REVIEW

**Comment by khvzak** [comment]
Thanks for the PR!

I was thinking about it and probably will prefer a bit more flixible approach by having `AsChunk` implemented for `Path`.
I see it requires some changes in the trait and in other parts but eventually it would be a win by providing a unified interface to load chunks, as:
```rust
lua.load(Path::new("./abc.lua")).exec();
```

**Comment by LordMZTE** [comment]
I think that's a great idea, and it was actually what I tried initially, however, I ran into a few issues with this:
- The `AsChunk` implementation for `Path` conflicts with the current blanket impl on `AsRef<[u8]>`, as path also implements that, but we can't use the blanket impl, since `Path` must be treated differently.
- Changing the `source` field of `Chunk` to an enum type with variants for a path and source code would require major refactoring, as a lot of code assumes it to be source code, and does stuff with that code (such as prepending a `return`).
    - This change to `Chunk` also requires changes in `AsChunk`, so that the `source` method returns this enum type

So that's quite a lot of breaking changes. Please let me know how I should proceed on these, and I'll get to work!

**Comment by sondr3** [comment]
Any chance of getting this merged/what's needed? This would be really helpful for a project I'm working on. 😅

**Comment by khvzak** [comment]
> Any chance of getting this merged/what's needed? This would be really helpful for a project I'm working on. 😅

Oh, this is already supported since v0.8, you can use `lua.load(std::path::Path::new("file.lua")).exec().unwrap();`

**Pull request closed without merging**
